name: Pages

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install cv
      run: go install github.com/preferit/cv@latest

    - name: Build CV
      run: ./steps.sh dist
      
